# Generated by Django 2.2.4 on 2019-09-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20190919_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_item',
            field=models.CharField(max_length=20),
        ),
    ]
